### PR TITLE
Fix Latte Inconsistencies & Rename Folders to Enforce Consistency

### PR DESCRIPTION
**Pull request by Cequallium**
#### Details:
- Splash-screen drop-shadow is no longer misaligned.
- Latte Splash-screen no longer uses Mocha Catppuccin logo
- Made all Splash-screens have legible drop-shadows
- Makes all folder names start with a capital character
- Makes Modern Aurorae theme smaller.
- Small Fixes to the Installer

#### Todo:
- [x] Remove "TODO:" 's in splash.qml

### CODE REVIEW

**Review by nekowinston — CHANGES_REQUESTED** [review]
Since this PR is already touching all of the shell scripts again, I'd love to see them all get linted with `shellcheck`.
That would also include replacing `#!/bin/bash` with `#!/usr/bin/env bash`

**Comment by Cequallium** [comment]
I do use the shellcheck lint engine in vscode, will update bin/bash.

**Review by nekowinston — APPROVED** [review]
Looks good now, thanks!

**Comment by Sourcastic** [comment]
Hmm, just tested this. I think the modern theme has a few problems. The directory name and the rc file's name don't seem to match. I also think there is an extra file in Resources/Aurorae/Common.

**Comment by Sourcastic** [comment]
Thanks for these changes. It seems to work now. I'll merge it. We'll merge it into main after I make a few changes to the readme when I get time.

Thanks for these fixes :D

**Pull request merged**
